spring:
 redis:
  database: 0
  timeout: 30000000
  pool:
   max-idle: 100 #最大空闲连接数
   min-idle: 8
   max-total: 1000 #最大连接数
   max-max-active: 4
   max-wait-millis: -1
  cluster:
   nodes: 192.168.5.199:7000,192.168.5.199:7001,192.168.5.199:7002,192.168.5.199:7003
   #nodes: 122.114.59.76:7000,122.114.59.76:7001,122.114.59.76:7002,122.114.59.76:7003
 thymeleaf:
  cache: false
  encoding: UTF-8
  content-type: text/html
  mode: LEGACYHTML5
 mvc:
  view:
   prefix: /WEB-INF/jsp/
   suffix: .jsp
   static-path-pattern: /webapp/WEB-INF/jsp/**
#   prefix: /static/jsp/
#   suffix: .jsp
#   static-path-pattern: /resources/static/**
 http:
  encoding:
   force: true
   charset: UTF-8
   enabled: true
 profiles:
  active: dev
 dsuser:
  url: jdbc:oracle:thin:@116.255.186.112:1521:orcl
  username: amoski_user
  password: YW1vc2tpX3VzZXI=
  driver-class-name: oracle.jdbc.OracleDriver
  max-active: 50
  max-idle: 50
  min-idle: 60000
  initial-size: 10
  validation-query: select 1 from dual
  test-on-borrow: true
  test-on-return: true
  test-while-idle: true
 application:
  name: AmoskiWebUser
 boot:
  admin:
   context-path: /admin
server:
 port: 8088 #指定该Eureke实例的端口
eureka:
 instance:
  preferIpAddress: true
  instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  leaseRenewalInseconds: 1
  leaseExpirationDurationInseconds: 3
 client:
  serviceUrl:
#   defaultZone: http://122.114.91.150:8761/eureka/
   defaultZone: http://localhost:8761/eureka/
#   defaultZone: http://192.168.5.178:8760/eureka/
#   defaultZone: http://192.168.5.155:8761/eureka/ #正式服务器
  server:
   enableSelfPreservation: false
   evictionIntervalTimerInMs: 36000
#  logging:
#   config: classpath:logback-boot.xml
#logging:
# level: info
# config: classpath:logback-boot.xml