spring:
 mvc:
  view:
   prefix: /WEB-INF/
   suffix: .jsp
   static-path-pattern: /webapp/WEB-INF/jsp/**
 http:
  encoding:
   force: true
   charset: UTF-8
   enabled: true
 profiles:
  active: dev
 dsuser:
  url: jdbc:oracle:thin:@192.168.5.163:1521:orcl
  #url: jdbc:oracle:thin:@116.255.186.112:1521:orcl #正式服务器
  username: amoski_activity
  password: YW1vc2tpX3VzZXI=
  #password: d3VzaXlhb21heXVxaW5nbG9uZ2Rhbg==
  driver-class-name: oracle.jdbc.OracleDriver
  max-active: 50
  max-idle: 50
  min-idle: 60000
  initial-size: 10
  validation-query: select 1 from dual
  test-on-borrow: true
  test-on-return: true
  test-while-idle: true
 application:
  name: AmoskiWebActivity
 boot:
  admin:
   context-path: /admin
server:
 port: 8555 #指定该Eureke实例的端口
eureka:
 instance:
  preferIpAddress: true
  instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  leaseRenewalInseconds: 1
  leaseExpirationDurationInseconds: 3
 client:
  serviceUrl:
   defaultZone: http://192.168.5.243:8761/eureka/
   #defaultZone: http://localhost:8761/eureka/
  server:
   enableSelfPreservation: false
   evictionIntervalTimerInMs: 30000
#  logging:
#   config: classpath:logback-boot.xml